name: advent-of-code
version: 0.1.0.0
dependencies:
  - base
  - vector
  - containers
  - parallel
  - deepseq
  - optparse-applicative
  - filepath 
  - directory
  - template-haskell
  - mtl
  - megaparsec
  - text
  - transformers
  - array

ghc-options:
  - -Wall
  - -O2
  - -threaded
  - -rtsopts

executables:
  aoc-exe:
    main: Main.hs
    source-dirs: 
      - app
      - src
    other-modules:
      - Days
      - Grid
      - TestUtils
      - Util
      - Days.Day02
      - Days.Day03
      - Days.Day04
      - Days.Day05
      - Days.Day06
      - Days.Day07
      - Days.Day08
      - Days.Day09
      - Days.Day10
      - Days.Day11
      - Days.Day12
      - Days.Day13
      - Days.Day14
      - Days.Day15
      - Days.Day16
      - Days.Day17
      - Days.Day18
      - Days.Day19
      - Days.Day20
      - Days.Day21
      - Days.Day22
      - Days.Day23
      - Days.Day24
    ghc-options:
      - -main-is Main